language: java
install: true
script: mvn clean verify --settings .travis.settings.xml -B -U -V
deploy:
  provider: script
  script: mvn deploy --settings .travis.settings.xml -DskipTests=true -B -V
  skip_cleanup: true
  on:
    repo: metaborg/log
    tags: true
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: CFXQeYnuu9Y4vGvnXZq1FKd3yax44epf/eqP6JeVwvrAMM3+xDlqIYmDx0sImNmKoJUGpFmn2MmmtQCaYPwPOxAh9akx76NTugGmBOCYvm8xkZ9TYdbqFooszzeYF8IcruTd/FvF3OdqelcnhZGtQxKhYounqjh2lrfE2+eT8GyoMd2oTAgN4COZdw5Y4i76jIbQQXh55ltIAYfK+RjJAsRWfW20n1ShY0fjTrbpe1xHMG3KkLbBE99Y2n5DRdL2OmrzWAfq7+/LhdhwFkoqGG+6kVxPLmtJHcLdYZyBS0m6tlmGUYAludyr5skfVm1xTw81IWS98MDWV8qYQHB6/xCZiT0DX8mowDxuKNHwy7pQ3LUKI7NqberuygifmOfcPhgz50LBWtNxB/ufSCREHemBuRr4oLZSAxM3stacD/yyUQKry0WOacxQHTSTx4CTcBTYBBLWdrZBuFVzbnEmtmsAo0oSYEXrPh5r6tV8u2iqOek6zYUs3Bnha/XNjG68RDAr/h69Tro0hy6J/JiJvpVIW/jVAe2czzuOu1baPtBXk/R4ip15BugMFfNyy+SZE1vNGICwUe8XWPXQigW2TXDHm8rrhEU9DtDUN70l4HMsIe9PJ2x81b7NL57sM+X33bFlKwVXMcJUn4aCj1aE0PbHwrVKHMiEaC3O2DHdxpE=
  - secure: eenqDw4DwU6pjARQKlbt+Rdvhrxv0gQTbStx94toTL6OyFQoNQNat+IllTfYYvmQqecfy9K0zClZ4xABTChOHZoV/vST7ogGzqC+fbUTP8u3jP8uYOIYb+D9YRN9n8y7SOBwcrtc3340M93sFApoi8h/aF+2XAuFy9EjH0DbvlxjQix7z2BRZkSL4qS26e6b5VrVyXeBYFhOCTSJvJAFEvPeKOGfLvvf+DpN2UzIArvMq2ipS4ZyKof3ErTlgSHPDQj9JFX41Z9FOXtNftoIOK3KqtqYLRAhyq/yOWFnWpSTmUR5+75tIcIepXlWS4Tfem4xcowYKC3l1s0SLJKYkO94WGCnvkY2rghJgYA9PXTrJwE8sPCXVAYY3sXwSw+GeqwIOexzLD6rxS5JDn9K5JNjSZa8Ae3IbmkgTIeFXvrsAlYGT+3yvDnYyQYiA2SWdCM6Qq1dM3VKnLIp5slNBQps/h/adMvQztq093OJAcw1HjfeARHmVvPw/+F7e6nc1slF8kYwSz8uyBVj16L/RrFtb7TT3X8VfN5hn6/vXvuorbv0UGQzC6KwbBmTIetAELOtAMSOU09oS6ekWA3K2Au9UjJk/17s6+X3+Z6IWQd14T6wWMfTvOVajkVmdokm/ydhlQyWA7zJbQ60s2YoRM5ZFkVX4c8UR1kpDqaR65I=
