language: java
install: true
script: mvn clean verify --settings .travis.settings.xml -B -U -V
deploy:
  provider: script
  script: mvn deploy --settings .travis.settings.xml -DskipTests=true -B -V
  skip_cleanup: true
  on:
    repo: metaborg/log
    tags: true
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: vFESTwnpSmv+9pcImhpZOOrcQohiRhEar0FpFP9yb7/vQyDv0rB/++m2v2Zt0wvwDFwEXp8XMizkcE6JRXqQha2HacYLCm7gwFcGMWxe1QOqCJgNz3gW6EEwcKoRlWXUpwv8yONDaJCLtrxcwWT2IMjnUZxZpBw7j5BIjiUmoOr12XX6+kwd1lrzeT7cClQOP3y4dzA85sKIIV4n6CRV4ypOZzAaZdcmnTwwSw62bJy8g2ll5YuOsJEMmlQohVHWGVIhNA16oxCOOv7deKfUMoBJN61wpNLhSdeCl60rWbBfyZ8BICQwV9W0RcddwzKazPdf5POln0v1pLa2unfpgA8Fplvg4EDY42akIQ2BH2E9uMdNZvGRqJbf3Xif8E4bnQXJRF4EJOxNWCPpv1TmdLBtT9aGbyoZbxdq53DESdSyUuWXFa59GTjTyqVhJImdG4H1/qYkahKZLGJaE4WwYmokTfPiVv5GlGrlmqKOF8iUVWvE2rYHRIsod9iEhdF0In6EfuT7dY4Gg+GNJzIyzh4zK2KnfZdGvrKCMJ+SOlJ5rOZcyP87GKu+5KfEx4F5vyCaXqwipRE9IOHI1VsdpX50v6TjBajy5JMBXhV+TPeHz5Xb2Sq7ZjiqgW7+TtNoFeOLl2wfJ++CP5WvoU3wP5ShRRKs18pfvrbD8+zOEqM=
  - secure: m2GfVUx/OfJrEy5RZ4U4br9eyn7PKNDFTy/8w0I047gKQWDLUxqNGLApvUjvS6A2X2DjjGGTRyV2+YKbMpb8/S+ckOqM0u8kj7cs3nAcPIOHqa/E58IszkNV79A2P0fb+gD/UBunb0EaUbUxEkoxWQmOyTL9+oexwTfyGOOjGjbsOhSI/ozeBY1nvDm8vYnQg1oh/PDQktZIPalZImF9oF3/IwPgNDtCB6BPcGZ6cd9x+6u9xy1K42pYf04LM194rDhmKQpHO1u1l+SdiKhH7Cr8aSXyUgYliy5EsfqKv69Twl4RGt12C/MJ5i8B+0WCYtvxDKco89Al+eXs8fZd8m0Rv1L4JxhvMVmNanFmOdl4pB1ZChfnOHPXDJyC6HP8fvdfDuao6QJ7CBapFZ7NF9WZz+WHJ3TN9ufHRE6e2rjiWlgFPO3fksYxzptl7QPKSLC+UxD2mgNHIUthh0N+qrGTwfhkL9cn6M1e5ZsX41RC0WOo6KLNL7dwUNzWZpq1i/I+k4k5k1hRKIDTPeA1iSujNnoPK2ltw2Ugx2MzW6bEYZmatqEhqcaBfJKcrLrr4yJhAKor8C6dCAFY09m2j6PtelboUqZ1tHpZybINlrvrG3aP2JqBhqHmOoN5bGSs6DBAG0dU/hekHe/TnbJnfRPOysmOiFNlPLP7bWDgq/c=
